'use client';
import { useEffect, useState } from 'react';
import { api, getApiErrorMessage } from '@/lib/api';
import { Button } from '@/components/Button';
import { Input } from '@/components/Input';
import type { FacultyOption } from '@/types/api';
export default function UniversitySettingsPage(){ const [items,setItems]=useState<FacultyOption[]>([]); const [faculty,setFaculty]=useState(''); const [facultyEn,setFacultyEn]=useState(''); const [major,setMajor]=useState(''); const [majorEn,setMajorEn]=useState(''); const [facultyId,setFacultyId]=useState(''); const [error,setError]=useState('');
 const load=()=>api.get<FacultyOption[]>('/universities/issuer/mine/faculties').then(r=>setItems(r.data)).catch(e=>setError(getApiErrorMessage(e))); useEffect(()=>{load()},[]);
 async function addFaculty(){try{await api.post('/universities/issuer/faculties',{nameTh:faculty,nameEn:facultyEn||undefined});setFaculty('');setFacultyEn('');load()}catch(e){setError(getApiErrorMessage(e))}}
 async function addMajor(){try{await api.post('/universities/issuer/majors',{facultyId,nameTh:major,nameEn:majorEn||undefined});setMajor('');setMajorEn('');load()}catch(e){setError(getApiErrorMessage(e))}}
 async function toggle(kind:'faculties'|'majors',id:string,isActive:boolean){await api.patch(`/universities/issuer/${kind}/${id}/active`,{isActive});load()}
 return <div className="space-y-6"><div><h2 className="text-2xl font-bold text-slate-800">คณะและสาขาวิชา</h2><p className="mt-2 text-sm text-slate-500">กำหนดตัวเลือกที่นักศึกษาจะใช้ตอนลงทะเบียน</p></div>{error&&<div className="rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}<div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="font-bold">เพิ่มคณะ</h3><div className="mt-4 space-y-3"><Input label="ชื่อคณะ (ภาษาไทย)" value={faculty} onChange={e=>setFaculty(e.target.value)} required/><Input label="ชื่อคณะ (ภาษาอังกฤษ)" value={facultyEn} onChange={e=>setFacultyEn(e.target.value)}/><Button onClick={addFaculty}>เพิ่มคณะ</Button></div></section><section className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="font-bold">เพิ่มสาขาวิชา</h3><div className="mt-4 space-y-3"><label className="block text-sm font-medium">คณะ<select className="mt-1 h-10 w-full rounded-lg border px-3" value={facultyId} onChange={e=>setFacultyId(e.target.value)}><option value="">เลือกคณะ</option>{items.filter(x=>x.isActive).map(x=><option key={x.id} value={x.id}>{x.nameTh}</option>)}</select></label><Input label="ชื่อสาขา (ภาษาไทย)" value={major} onChange={e=>setMajor(e.target.value)} required/><Input label="ชื่อสาขา (ภาษาอังกฤษ)" value={majorEn} onChange={e=>setMajorEn(e.target.value)}/><Button onClick={addMajor}>เพิ่มสาขา</Button></div></section></div><section className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="font-bold">รายการคณะและสาขา</h3><div className="mt-4 space-y-4">{items.map(f=><div key={f.id} className="rounded-xl border p-4"><div className="flex items-center justify-between"><div className="font-semibold">{f.nameTh}</div><button className="text-sm text-blue-600" onClick={()=>toggle('faculties',f.id,!f.isActive)}>{f.isActive?'ปิดใช้งาน':'เปิดใช้งาน'}</button></div><div className="mt-3 space-y-2">{f.majors.map(m=><div key={m.id} className="flex justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>{m.nameTh}</span><button className="text-blue-600" onClick={()=>toggle('majors',m.id,!m.isActive)}>{m.isActive?'ปิด':'เปิด'}</button></div>)}</div></div>)}</div></section></div> }
